all:
	javac -classpath ".$(CPSEP)../../" *.java

r1:
	java -classpath ".$(CPSEP)../../" IF1

r2:
	java -classpath ".$(CPSEP)../../" IF2

r3:
	java -classpath ".$(CPSEP)../../" IF3

r4:
	java -classpath ".$(CPSEP)../../" PB1

t1:
	java -classpath ".$(CPSEP)../../" T1

