all:
	javac -classpath ".;../jar/jass.jar" *.java

run:
	java -classpath ".;../jar/jass.jar" Pyramid ../data/bell4.sy ../data/desklamp.sy ../data/sword2.sy ../data/equalTempMajorTriad.sy ../data/sword1.sy


