/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Groove */

#ifndef _Included_Groove
#define _Included_Groove
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Groove
 * Method:    getPositionOfNeedleFromHardware
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Groove_getPositionOfNeedleFromHardware
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
