all:
	javac -classpath ".$(CPSEP)../../" *.java

run:
	java -classpath ".$(CPSEP)../../" Bang ../data/bell4.sy ../data/cos20ms.wav ../data/white.wav ../data/roll.wav

run2:
	java -classpath ".$(CPSEP)../../" Bang ../data/p_bell4.sy ../data/cos20ms.wav ../data/white.wav ../data/roll.wav

run3:
	java -classpath ".$(CPSEP)../../" Bang ../data/clayvase-nobogus2.sy ../data/cos20ms.wav ../data/white.wav ../data/roll.wav

run4:
	java -classpath ".$(CPSEP)../../" Bang D:/aakees/ubc/modalFitter/sy/vase/vasep0.sy ../data/hit50ms.wav ../data/white.wav ../data/roll.wav

run5:
	java -classpath ".$(CPSEP)../../" Bang D:/aakees/ubc/modalFitter/sy/vase/vaseMerged.sy ../data/hit50ms.wav ../data/white.wav ../data/roll.wav
