all:
	javac -classpath ".$(CPSEP)../../" *.java

r:
	java -classpath ".$(CPSEP)../../" Bubbles 50  128 44100 ../data/foobar.not.exist

r2:
	java -classpath ".$(CPSEP)../../" Bubbles 50  128 44100 ../data/timecapsule2.sy


