/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jass_render_RTAudioFullDuplexRtAudio */

#ifndef _Included_jass_render_RTAudioFullDuplexRtAudio
#define _Included_jass_render_RTAudioFullDuplexRtAudio
#ifdef __cplusplus
extern "C" {
#endif
#undef jass_render_RTAudioFullDuplexRtAudio_MIN_PRIORITY
#define jass_render_RTAudioFullDuplexRtAudio_MIN_PRIORITY 1L
#undef jass_render_RTAudioFullDuplexRtAudio_NORM_PRIORITY
#define jass_render_RTAudioFullDuplexRtAudio_NORM_PRIORITY 5L
#undef jass_render_RTAudioFullDuplexRtAudio_MAX_PRIORITY
#define jass_render_RTAudioFullDuplexRtAudio_MAX_PRIORITY 10L
#undef jass_render_RTAudioFullDuplexRtAudio_bigEndian
#define jass_render_RTAudioFullDuplexRtAudio_bigEndian 0L
/*
 * Class:     jass_render_RTAudioFullDuplexRtAudio
 * Method:    initNativeSound
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_jass_render_RTAudioFullDuplexRtAudio_initNativeSound
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jass_render_RTAudioFullDuplexRtAudio
 * Method:    closeNativeSound
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jass_render_RTAudioFullDuplexRtAudio_closeNativeSound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jass_render_RTAudioFullDuplexRtAudio
 * Method:    writeReadNativeSoundFloat
 * Signature: (J[FI[FI)V
 */
JNIEXPORT void JNICALL Java_jass_render_RTAudioFullDuplexRtAudio_writeReadNativeSoundFloat
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
