/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jass_render_RTAudioIn */

#ifndef _Included_jass_render_RTAudioIn
#define _Included_jass_render_RTAudioIn
#ifdef __cplusplus
extern "C" {
#endif
#undef jass_render_RTAudioIn_MIN_PRIORITY
#define jass_render_RTAudioIn_MIN_PRIORITY 1L
#undef jass_render_RTAudioIn_NORM_PRIORITY
#define jass_render_RTAudioIn_NORM_PRIORITY 5L
#undef jass_render_RTAudioIn_MAX_PRIORITY
#define jass_render_RTAudioIn_MAX_PRIORITY 10L
#undef jass_render_RTAudioIn_bigEndian
#define jass_render_RTAudioIn_bigEndian 0L
/*
 * Class:     jass_render_RTAudioIn
 * Method:    initNativeSound
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_jass_render_RTAudioIn_initNativeSound
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jass_render_RTAudioIn
 * Method:    readNativeSoundFloat
 * Signature: (J[FI)V
 */
JNIEXPORT void JNICALL Java_jass_render_RTAudioIn_readNativeSoundFloat
  (JNIEnv *, jobject, jlong, jfloatArray, jint);

/*
 * Class:     jass_render_RTAudioIn
 * Method:    closeNativeSound
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jass_render_RTAudioIn_closeNativeSound
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
