/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jass_render_RTPlay */

#ifndef _Included_jass_render_RTPlay
#define _Included_jass_render_RTPlay
#ifdef __cplusplus
extern "C" {
#endif
#undef jass_render_RTPlay_MIN_PRIORITY
#define jass_render_RTPlay_MIN_PRIORITY 1L
#undef jass_render_RTPlay_NORM_PRIORITY
#define jass_render_RTPlay_NORM_PRIORITY 5L
#undef jass_render_RTPlay_MAX_PRIORITY
#define jass_render_RTPlay_MAX_PRIORITY 10L
#undef jass_render_RTPlay_bigEndian
#define jass_render_RTPlay_bigEndian 0L
#undef jass_render_RTPlay_DEFAULT_BUFFERSIZE
#define jass_render_RTPlay_DEFAULT_BUFFERSIZE 1024L
/*
 * Class:     jass_render_RTPlay
 * Method:    initNativeSound
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_jass_render_RTPlay_initNativeSound
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jass_render_RTPlay
 * Method:    writeNativeSoundFloat
 * Signature: (J[FI)V
 */
JNIEXPORT void JNICALL Java_jass_render_RTPlay_writeNativeSoundFloat
  (JNIEnv *, jobject, jlong, jfloatArray, jint);

/*
 * Class:     jass_render_RTPlay
 * Method:    closeNativeSound
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jass_render_RTPlay_closeNativeSound
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
