/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jass_render_MicroTime */

#ifndef _Included_jass_render_MicroTime
#define _Included_jass_render_MicroTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jass_render_MicroTime
 * Method:    getMicroTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_jass_render_MicroTime_getMicroTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
