all:
	javac -classpath ".$(CPSEP)../../" *.java

run:
	java -classpath ".$(CPSEP)../../" Engine ../data/stick.sy 

run2:
	java -classpath ".$(CPSEP)../../" Engine ../data/metalobject3.syenSortp_5.sy 
