
all:
	javac -classpath ".$(CPSEP)../../" *.java


1:
	java -classpath ".$(CPSEP)../../" DemoMousePictureExplore gfx/qt-colors.jpg 45.1 ../data/ell4.sy 512

2:
	java -classpath ".$(CPSEP)../../" DemoMousePictureExplore gfx/gogh2.jpg 45.1 ../data/ell4.sy 512

3:
	java -classpath ".$(CPSEP)../../" DemoMousePictureExplore gfx/generic-solid-color-cpos.jpg 45.1 ../data/ell4.sy 512

4:
	java -classpath ".$(CPSEP)../../" DemoMousePictureExplore gfx/watches.jpg 45.1 ../data/ell4.sy 512

5:
	java -classpath ".$(CPSEP)../../" DemoMousePictureExplore gfx/desktop1.jpg 45.1 ../data/ell4.sy 512



