all:
	javac -classpath ".$(CPSEP)../../" *.java

js:
	java -classpath ".$(CPSEP)../../" LatencyOutTest js 8 1536

rt:
	java -classpath ".$(CPSEP)../../" LatencyOutTest rtaudio 8 1024

as:
	java -classpath ".$(CPSEP)../../" LatencyOutTest asio 8  0


