all:
	javac -classpath ".$(CPSEP)../../" *.java

r1:
	java -server -classpath ".$(CPSEP)../../" DemoModalBenchMark

r2:
	java -server  -classpath ".$(CPSEP)../../" DemoModalBenchMark1Contact

r3:
	java -classpath ".$(CPSEP)../../" DemoModalBenchMark2