all:
	javac -classpath ".$(CPSEP)../../" *.java

r:
	java -classpath ".$(CPSEP)../../" VTDemo 5  .17 44100

w:
	java -classpath ".$(CPSEP)../../" VTDemoW 3 .17 44100

r2:
	java -classpath ".$(CPSEP)../../" VTDemo2  .17 44100

r3:
	java -classpath ".$(CPSEP)../../"  VTDemo2Root 
