/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RTPlay */

#ifndef _Included_RTPlay
#define _Included_RTPlay
#ifdef __cplusplus
extern "C" {
#endif
#undef RTPlay_bigEndian
#define RTPlay_bigEndian 0L
/* Inaccessible static: mixer */
#undef RTPlay_DEFAULT_BUFFERSIZE
#define RTPlay_DEFAULT_BUFFERSIZE 1024L
/* Inaccessible static: class_00024javax_00024sound_00024sampled_00024SourceDataLine */
/*
 * Class:     RTPlay
 * Method:    initNativeSound
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_synth_render_RTPlay_initNativeSound
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     RTPlay
 * Method:    writeNativeSound
 * Signature: (J[SI)V
 */
JNIEXPORT void JNICALL Java_synth_render_RTPlay_writeNativeSound
  (JNIEnv *, jobject, jlong, jshortArray, jint);

/*
 * Class:     RTPlay
 * Method:    closeNativeSound
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_synth_render_RTPlay_closeNativeSound
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
